---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: tenant2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: ealen/echo-server:latest
          imagePullPolicy: IfNotPresent
          name: echoserver
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: TENANT
              value: "tenant2"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: tenant2
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: echoserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-tenant2
  namespace: tenant2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /tenant2(/|$)(.*)
            backend:
              service:
                name: echoserver
                port:
                  number: 8080
---

